"""Folder notes, stored in the folder's own `README.md`.

A per-file sidecar records intent about one part. A folder note records intent
about a sub-system: what this tree is, which assembly is primary, what is still
unverified. The repository already has that surface — the per-folder
`README.md` that `scripts/generate_readmes.py` seeds and MkDocs links — so a
note written here is the same file the owner reads on GitHub, not a second
parallel store.

The generator writes `AUTOGEN_MARKER` at the top of a file it created and never
rewrites a file whose first line is *not* that marker. Saving a note therefore
strips the marker: from that save onwards the file reads as manually edited and
the generator must leave it alone. `tests/test_foldernote.py` pins both halves
of that contract against the generator itself.

Nothing here writes to a CAD file.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

FOLDER_NOTE_NAME = "README.md"
#: Must stay byte-identical to `AUTOGEN_NOTICE`'s first line in
#: `scripts/generate_readmes.py`; a test asserts it.
AUTOGEN_MARKER = "<!-- This file was generated by scripts/generate_readmes.py -->"
EXCERPT_LENGTH = 150

# Lines that are structure rather than prose, so never the note's first sentence.
_SKIP_PREFIXES = ("#", ">", "-", "*", "|", "```", "<!--", "_No ")


class FolderNoteError(ValueError):
    """The folder note is not something this tool is willing to write."""


@dataclass(frozen=True)
class FolderNote:
    path: Path
    text: str
    generated: bool

    @property
    def excerpt(self) -> str:
        return note_excerpt(self.text)


def folder_note_path(folder: Path | str) -> Path:
    return Path(folder) / FOLDER_NOTE_NAME


def is_generated(text: str) -> bool:
    """True when the text still carries the generator's own marker."""

    return text.lstrip("﻿").lstrip().startswith(AUTOGEN_MARKER)


def strip_autogen_marker(text: str) -> str:
    """Drop the generator's leading notice so the file reads as manually edited.

    Only the contiguous comment block at the very top goes; an HTML comment the
    author typed further down is their content and is left alone.
    """

    body = text.lstrip("﻿")
    if not is_generated(body):
        return text
    lines = body.splitlines(keepends=True)
    index = 0
    while index < len(lines):
        line = lines[index].strip()
        if not (line.startswith("<!--") and line.endswith("-->")):
            break
        index += 1
    return "".join(lines[index:]).lstrip("\n")


def note_excerpt(text: str, limit: int = EXCERPT_LENGTH) -> str:
    """First line of real prose, or '' when the file is only a generated index.

    A generated `README.md` is headings, bullet lists, and HTML placeholder
    comments, so it deliberately yields nothing: an empty excerpt means "no
    folder note yet", which is the honest reading.
    """

    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith(_SKIP_PREFIXES):
            continue
        return line if len(line) <= limit else line[: limit - 1].rstrip() + "…"
    return ""


def read_folder_note(folder: Path | str) -> FolderNote | None:
    """Read a folder's note, or None when the folder has no `README.md`."""

    path = folder_note_path(folder)
    if not path.is_file():
        return None
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        raise FolderNoteError(f"the folder note could not be read: {exc}") from exc
    return FolderNote(path=path, text=text, generated=is_generated(text))


def write_folder_note(folder: Path | str, text: str) -> FolderNote:
    """Write a folder note, stripping the generator marker so it stays manual."""

    path = folder_note_path(folder)
    if not path.parent.is_dir():
        raise FolderNoteError("the folder does not exist")
    body = strip_autogen_marker(text).replace("\r\n", "\n").strip("\n")
    if not body.strip():
        raise FolderNoteError("an empty note would erase the folder's README.md")
    final = body + "\n"
    path.write_text(final, encoding="utf-8", newline="\n")
    return FolderNote(path=path, text=final, generated=False)
