#!/usr/bin/env python3
"""
generate_readmes.py
-------------------
Generate README.md files and an optional INDEX.md for an Autodesk Inventor
engineering workspace.

Rules:
  - Never rename, move, or modify .iam / .ipt files.
  - Only writes README.md (per folder) and root INDEX.md.
  - Creates / updates .gitignore at the repository root.
  - Treats every other file as read-only.

Usage:
    python scripts/generate_readmes.py [--root PATH] [--dry-run] [--no-index]
"""

import argparse
import datetime
import os
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

GITIGNORE_RULES = """\
# Autodesk Inventor cache / lock files
*.lck
*.lock
*.tmp
*.bak
~*
Thumbs.db
Desktop.ini

# Old version archives (recursive)
**/OldVersions/
"""

AUTOGEN_NOTICE = (
    "<!-- This file was generated by scripts/generate_readmes.py -->\n"
    "<!-- Do not edit by hand; re-run the script to refresh. -->\n"
)

# Folder names (exact, case-insensitive) that mark a vendor/import subtree.
# The matching folder AND all its descendants are skipped entirely.
SKIP_DIR_NAMES = {"step", "steps", "stp"}

# When Inventor imports a STEP file it generates generic part/assembly names.
# If most files in a folder match these stems the folder is an imported model,
# not a custom engineering design.
STEP_IMPORT_STEMS = {"body", "group", "solid", "part", "surface", "component"}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def find_main_iam(iams: list[Path]) -> Path | None:
    """Pick the most likely 'main' assembly from a list of .iam paths."""
    if not iams:
        return None
    # 1. prefer filenames containing 'main' (case-insensitive)
    for p in iams:
        if "main" in p.stem.lower():
            return p
    # 2. largest file by size
    try:
        by_size = sorted(iams, key=lambda p: p.stat().st_size, reverse=True)
        return by_size[0]
    except OSError:
        pass
    # 3. first alphabetically
    return sorted(iams, key=lambda p: p.name.lower())[0]


def rel_link(from_dir: Path, target: Path) -> str:
    """Return a relative markdown link path from from_dir to target."""
    return os.path.relpath(target, from_dir).replace("\\", "/")


def is_content_center(folder: Path, root: Path) -> bool:
    """True if this folder is inside (or is) the ContentCenter subtree."""
    try:
        folder.relative_to(root / "ContentCenter")
        return True
    except ValueError:
        return False


def is_vendor_path(folder: Path, root: Path) -> bool:
    """True if the folder itself or any ancestor is a known vendor/import directory."""
    try:
        rel = folder.relative_to(root)
    except ValueError:
        return False
    return any(part.lower() in SKIP_DIR_NAMES for part in rel.parts)


def looks_like_step_import(iams: list[Path], ipts: list[Path]) -> bool:
    """
    True when the naming pattern suggests an auto-imported STEP model rather
    than a custom engineering design.

    Inventor names parts/assemblies "Body.ipt", "Body001.ipt", "Group.iam",
    "Group002.iam", etc. when importing STEP geometry.  If ≥ 50 % of the
    files in a folder share those generic stems, treat the folder as vendor
    storage and skip it.
    """
    files = iams + ipts
    if not files:
        return False
    generic = sum(
        1 for p in files
        if p.stem.lower().rstrip("0123456789 ") in STEP_IMPORT_STEMS
    )
    return generic / len(files) >= 0.5


def is_meaningful_folder(
    folder: Path, root: Path, iams: list[Path], ipts: list[Path]
) -> bool:
    """
    Noise-suppression heuristic.  Returns True only for folders that look like
    real engineering / project workspaces rather than imported components.

    Short-circuits to False if file naming looks like a STEP import (generic
    Body/Group stems), regardless of file counts.

    A folder qualifies if ANY of the following is true:
      - It is a direct child of the repository root  (always a project folder)
      - It contains multiple assemblies              (≥ 2 .iam)
      - It contains an assembly + multiple parts     (≥ 1 .iam and ≥ 2 .ipt)
      - It has subdirectories                        (suggests a sub-system tree)
    """
    # Direct children of root are always top-level project folders.
    if folder.parent == root:
        return True
    # Veto: auto-imported STEP geometry masquerading as assemblies.
    if looks_like_step_import(iams, ipts):
        return False
    if len(iams) >= 2:
        return True
    if len(iams) >= 1 and len(ipts) >= 2:
        return True
    subdirs = [d for d in folder.iterdir() if d.is_dir() and d.name != "OldVersions"]
    if subdirs:
        return True
    return False


def collect_iams_ipts(folder: Path) -> tuple[list[Path], list[Path]]:
    """Return (.iam files, .ipt files) directly inside folder (non-recursive)."""
    iams = sorted(folder.glob("*.iam"), key=lambda p: p.name.lower())
    ipts = sorted(folder.glob("*.ipt"), key=lambda p: p.name.lower())
    return iams, ipts


# ---------------------------------------------------------------------------
# README rendering
# ---------------------------------------------------------------------------

def render_readme(folder: Path, iams: list[Path], ipts: list[Path]) -> str:
    title = folder.name
    today = datetime.date.today().isoformat()
    main = find_main_iam(iams)

    lines: list[str] = []
    lines.append(AUTOGEN_NOTICE)
    lines.append(f"# {title}\n")
    lines.append(
        f"> Auto-generated index — {today}. "
        "Edit the placeholder sections below to add real documentation.\n"
    )

    # --- Assemblies --------------------------------------------------------
    lines.append("## Assemblies (`.iam`)\n")
    if iams:
        for p in iams:
            marker = " ⭐" if p == main else ""
            lines.append(f"- `{p.name}`{marker}")
        lines.append("")
    else:
        lines.append("_No assemblies found._\n")

    # --- Parts -------------------------------------------------------------
    lines.append("## Parts (`.ipt`)\n")
    if ipts:
        for p in ipts:
            lines.append(f"- `{p.name}`")
        lines.append("")
    else:
        lines.append("_No parts found in this folder._\n")

    # --- Placeholder sections ----------------------------------------------
    lines.append("## Purpose\n")
    lines.append("<!-- Describe what this assembly / sub-system is for. -->\n")

    lines.append("## Main Assemblies\n")
    if main:
        lines.append(f"- **`{main.name}`** — primary assembly (auto-detected)\n")
    else:
        lines.append("<!-- List the key .iam files and what they represent. -->\n")

    lines.append("## Notes\n")
    lines.append("<!-- Add any relevant design notes, revisions, or known issues. -->\n")

    lines.append("## Status\n")
    lines.append("<!-- e.g. In progress / Complete / Legacy / Archived -->\n")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# README for ContentCenter root
# ---------------------------------------------------------------------------

def render_content_center_readme(folder: Path) -> str:
    today = datetime.date.today().isoformat()
    # Collect all .iam / .ipt recursively under ContentCenter
    iams = sorted(folder.rglob("*.iam"), key=lambda p: p.name.lower())
    ipts = sorted(folder.rglob("*.ipt"), key=lambda p: p.name.lower())
    subfolders = sorted(
        [d for d in folder.iterdir() if d.is_dir()],
        key=lambda d: d.name.lower(),
    )

    lines: list[str] = []
    lines.append(AUTOGEN_NOTICE)
    lines.append("# ContentCenter\n")
    lines.append(
        f"> Auto-generated index — {today}. "
        "Shared library of reusable Inventor components.\n"
    )

    lines.append("## Library Categories\n")
    if subfolders:
        for d in subfolders:
            lines.append(f"- `{d.name}/`")
        lines.append("")

    lines.append(f"## Summary\n")
    lines.append(f"- **Assemblies (`.iam`):** {len(iams)}")
    lines.append(f"- **Parts (`.ipt`):** {len(ipts)}\n")

    lines.append("## Notes\n")
    lines.append(
        "This folder is the shared ContentCenter library for the PIHTI project.\n"
        "Components here are referenced by assemblies throughout the workspace.\n"
    )

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# .gitignore
# ---------------------------------------------------------------------------

def write_gitignore(root: Path, dry_run: bool) -> None:
    target = root / ".gitignore"
    if target.exists():
        existing = target.read_text(encoding="utf-8")
        # Check if our marker is already present
        if "Autodesk Inventor cache" in existing:
            print(f"  [skip]  .gitignore already contains Inventor rules")
            return
        new_content = existing.rstrip("\n") + "\n\n" + GITIGNORE_RULES
        action = "update"
    else:
        new_content = GITIGNORE_RULES
        action = "create"

    print(f"  [{action}] .gitignore")
    if not dry_run:
        target.write_text(new_content, encoding="utf-8")


# ---------------------------------------------------------------------------
# INDEX.md
# ---------------------------------------------------------------------------

def render_index(root: Path, index_entries: list[tuple[Path, Path | None]]) -> str:
    today = datetime.date.today().isoformat()
    lines: list[str] = []
    lines.append(AUTOGEN_NOTICE)
    lines.append("# PIHTI — Project Index\n")
    lines.append(
        f"> Auto-generated on {today}. "
        "Lists all folders containing Inventor assemblies.\n"
    )
    lines.append("| Folder | Main Assembly |")
    lines.append("|--------|---------------|")
    for folder, main in sorted(index_entries, key=lambda e: str(e[0]).lower()):
        rel_folder = os.path.relpath(folder, root).replace("\\", "/")
        readme_link = f"[{rel_folder}]({rel_folder}/README.md)"
        main_cell = f"`{main.name}`" if main else "_—_"
        lines.append(f"| {readme_link} | {main_cell} |")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main scan + generate
# ---------------------------------------------------------------------------

def run(root: Path, dry_run: bool, generate_index: bool) -> None:
    root = root.resolve()
    print(f"Root: {root}")
    if dry_run:
        print("  ** DRY RUN — no files will be written **\n")

    content_center = root / "ContentCenter"
    index_entries: list[tuple[Path, Path | None]] = []

    # --- .gitignore --------------------------------------------------------
    write_gitignore(root, dry_run)

    # --- Walk all directories ----------------------------------------------
    all_dirs = sorted(root.rglob("*"), key=lambda p: str(p).lower())
    visited_dirs: set[Path] = set()

    for path in all_dirs:
        if not path.is_dir():
            continue
        # Skip OldVersions everywhere
        if "OldVersions" in path.parts:
            continue
        folder = path

        # --- ContentCenter special handling --------------------------------
        if folder == content_center:
            readme = folder / "README.md"
            if readme.exists():
                print(f"  [exists] {readme.relative_to(root)}")
            else:
                print(f"  [write]  {readme.relative_to(root)}")
                if not dry_run:
                    readme.write_text(
                        render_content_center_readme(folder), encoding="utf-8"
                    )
            visited_dirs.add(folder)
            continue

        if is_content_center(folder, root):
            # skip all ContentCenter subfolders
            continue

        # Skip vendor / imported-component subtrees (STEP, STEPs, stp, …)
        if is_vendor_path(folder, root):
            continue

        # --- Regular folders -----------------------------------------------
        iams, ipts = collect_iams_ipts(folder)

        if not iams:
            continue

        # Noise suppression: skip single-component / helper folders
        if not is_meaningful_folder(folder, root, iams, ipts):
            print(f"  [noise]  {folder.relative_to(root)}")
            continue

        readme = folder / "README.md"
        if readme.exists():
            print(f"  [exists] {readme.relative_to(root)}")
        else:
            print(f"  [write]  {readme.relative_to(root)}")
            if not dry_run:
                readme.write_text(
                    render_readme(folder, iams, ipts), encoding="utf-8"
                )

        main = find_main_iam(iams)
        index_entries.append((folder, main))

    # --- INDEX.md ----------------------------------------------------------
    if generate_index:
        index_path = root / "INDEX.md"
        if index_path.exists():
            print(f"  [exists] INDEX.md")
        else:
            print(f"  [write]  INDEX.md")
            if not dry_run:
                index_path.write_text(
                    render_index(root, index_entries), encoding="utf-8"
                )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate README.md files for an Autodesk Inventor workspace."
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="Path to the repository root (default: parent of this script's folder)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned actions without writing any files",
    )
    parser.add_argument(
        "--no-index",
        dest="index",
        action="store_false",
        help="Skip generating INDEX.md at the repository root",
    )
    parser.set_defaults(index=True)
    args = parser.parse_args()
    run(args.root, args.dry_run, args.index)


if __name__ == "__main__":
    main()
