#!/usr/bin/env python3
"""
generate_readmes.py
-------------------
Generate README.md files and an optional INDEX.md for an Autodesk Inventor
engineering workspace.

Rules:
  - Never rename, move, or modify .iam / .ipt files.
  - Only writes README.md (per folder) and root INDEX.md.
  - Creates / updates .gitignore at the repository root.
  - Treats every other file as read-only.

Usage:
    python scripts/generate_readmes.py [--root PATH] [--dry-run] [--no-index]
"""

import argparse
import datetime
import os
from functools import partial
from pathlib import Path
from typing import Callable

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

GITIGNORE_RULES = """\
# Autodesk Inventor cache / lock files
*.lck
*.lock
*.tmp
*.bak
~*
Thumbs.db
Desktop.ini

# Old version archives (recursive)
**/OldVersions/
"""

AUTOGEN_MARKER = "<!-- This file was generated by scripts/generate_readmes.py -->"
AUTOGEN_NOTICE = (
    f"{AUTOGEN_MARKER}\n"
    "<!-- Editing this file (by hand or via the folder-note editor) claims it as "
    "your folder note; the generator will then leave it alone. -->\n"
)

# Folder names (exact, case-insensitive) whose entire subtree is outside the
# curated documentation surface: caches, staging, save history, and vendor
# support payloads.
SKIP_DIR_NAMES = {
    ".git",
    ".pihti-dedup",
    ".pytest_cache",
    "_site",
    "design data",
    "oldversions",
    "staging",
    "step",
    "steps",
    "stp",
    "templates",
}

# When Inventor imports a STEP file it generates generic part/assembly names.
# If most files in a folder match these stems the folder is an imported model,
# not a custom engineering design.
STEP_IMPORT_STEMS = {"body", "group", "solid", "part", "surface", "component"}


# ---------------------------------------------------------------------------
# Manual-edit detection
# ---------------------------------------------------------------------------

def is_autogenerated(text: str) -> bool:
    """True when the text still opens with this script's own marker."""
    return text.lstrip("﻿").lstrip().startswith(AUTOGEN_MARKER)


def is_manually_edited(path: Path) -> bool:
    """True for any README this script must never rewrite.

    Absence of the marker is the signal, which covers three cases with one
    rule: a hand-authored README that never came from here, a generated one the
    owner has since rewritten, and one saved through the pihti-dedup folder-note
    editor (which strips the marker on save for exactly this reason).

    An unreadable file is reported as manual. Refusing to touch a file we cannot
    inspect is the safe direction; the alternative silently destroys notes.
    """
    try:
        return not is_autogenerated(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError):
        return True


def write_generated(
    path: Path,
    render: Callable[[], str],
    root: Path,
    dry_run: bool,
    *,
    create: bool = True,
) -> None:
    """Write a generated file, never over content this script did not author.

    Every write in this script goes through here, so the manual-edit rule cannot
    be bypassed by adding a new output later. Marker-owned files are refreshed;
    `create=False` limits a run to those existing outputs. `render` is deferred
    because building a README costs a directory scan the skip path does not need.
    """
    if path.exists() and is_manually_edited(path):
        print(f"  [manual] {path.relative_to(root)}")
        return
    if not path.exists() and not create:
        return

    content = render()
    if path.exists() and path.read_text(encoding="utf-8") == content:
        print(f"  [current] {path.relative_to(root)}")
        return

    action = "refresh" if path.exists() else "write"
    print(f"  [{action}] {path.relative_to(root)}")
    if not dry_run:
        path.write_text(content, encoding="utf-8", newline="\n")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def find_main_iam(iams: list[Path]) -> Path | None:
    """Pick the most likely 'main' assembly from a list of .iam paths."""
    if not iams:
        return None
    # 1. prefer filenames containing 'main' (case-insensitive)
    for p in iams:
        if "main" in p.stem.lower():
            return p
    # 2. largest file by size
    try:
        by_size = sorted(iams, key=lambda p: p.stat().st_size, reverse=True)
        return by_size[0]
    except OSError:
        pass
    # 3. first alphabetically
    return sorted(iams, key=lambda p: p.name.lower())[0]


def rel_link(from_dir: Path, target: Path) -> str:
    """Return a relative markdown link path from from_dir to target."""
    return os.path.relpath(target, from_dir).replace("\\", "/")


def is_content_center(folder: Path, root: Path) -> bool:
    """True if this folder is inside (or is) the ContentCenter subtree."""
    try:
        folder.relative_to(root / "ContentCenter")
        return True
    except ValueError:
        return False


def is_vendor_path(folder: Path, root: Path) -> bool:
    """True if the folder or an ancestor is excluded generated-document baggage."""
    try:
        rel = folder.relative_to(root)
    except ValueError:
        return False
    return any(part.lower() in SKIP_DIR_NAMES for part in rel.parts)


def looks_like_step_import(iams: list[Path], ipts: list[Path]) -> bool:
    """
    True when the naming pattern suggests an auto-imported STEP model rather
    than a custom engineering design.

    Inventor names parts/assemblies "Body.ipt", "Body001.ipt", "Group.iam",
    "Group002.iam", etc. when importing STEP geometry.  If ≥ 50 % of the
    files in a folder share those generic stems, treat the folder as vendor
    storage and skip it.
    """
    files = iams + ipts
    if not files:
        return False
    generic = sum(
        1 for p in files
        if p.stem.lower().rstrip("0123456789 ") in STEP_IMPORT_STEMS
    )
    return generic / len(files) >= 0.5


def is_meaningful_folder(
    folder: Path, root: Path, iams: list[Path], ipts: list[Path]
) -> bool:
    """
    Noise-suppression heuristic.  Returns True only for folders that look like
    real engineering / project workspaces rather than imported components.

    Short-circuits to False if file naming looks like a STEP import (generic
    Body/Group stems), regardless of file counts.

    A folder qualifies if ANY of the following is true:
      - It is a direct child of the repository root  (always a project folder)
      - It contains multiple assemblies              (≥ 2 .iam)
      - It contains an assembly + multiple parts     (≥ 1 .iam and ≥ 2 .ipt)
      - It has subdirectories                        (suggests a sub-system tree)
    """
    # Direct children of root are always top-level project folders.
    if folder.parent == root:
        return True
    # Veto: auto-imported STEP geometry masquerading as assemblies.
    if looks_like_step_import(iams, ipts):
        return False
    if len(iams) >= 2:
        return True
    if len(iams) >= 1 and len(ipts) >= 2:
        return True
    subdirs = [d for d in folder.iterdir() if d.is_dir() and d.name != "OldVersions"]
    if subdirs:
        return True
    return False


def collect_iams_ipts(folder: Path) -> tuple[list[Path], list[Path]]:
    """Return (.iam files, .ipt files) directly inside folder (non-recursive)."""
    iams = sorted(folder.glob("*.iam"), key=lambda p: p.name.lower())
    ipts = sorted(folder.glob("*.ipt"), key=lambda p: p.name.lower())
    return iams, ipts


# ---------------------------------------------------------------------------
# README rendering
# ---------------------------------------------------------------------------

def render_readme(folder: Path, iams: list[Path], ipts: list[Path]) -> str:
    title = folder.name
    today = datetime.date.today().isoformat()
    main = find_main_iam(iams)

    lines: list[str] = []
    lines.append(AUTOGEN_NOTICE)
    lines.append(f"# {title}\n")
    lines.append(
        f"> Generated CAD inventory — {today}. "
        "To document purpose or status, edit this file or use the folder-note "
        "editor. Once authored, the generator will leave it alone.\n"
    )

    if main:
        lines.append("## Main Assembly\n")
        lines.append(f"- **`{main.name}`** — selected from the assemblies below\n")

    # --- Assemblies --------------------------------------------------------
    lines.append("## Assemblies (`.iam`)\n")
    if iams:
        for p in iams:
            lines.append(f"- `{p.name}`")
        lines.append("")
    else:
        lines.append("_No assemblies found._\n")

    # --- Parts -------------------------------------------------------------
    lines.append("## Parts (`.ipt`)\n")
    if ipts:
        for p in ipts:
            lines.append(f"- `{p.name}`")
        lines.append("")
    else:
        lines.append("_No parts found in this folder._\n")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# README for ContentCenter root
# ---------------------------------------------------------------------------

def render_content_center_readme(folder: Path) -> str:
    today = datetime.date.today().isoformat()
    # Collect all .iam / .ipt recursively under ContentCenter
    iams = sorted(folder.rglob("*.iam"), key=lambda p: p.name.lower())
    ipts = sorted(folder.rglob("*.ipt"), key=lambda p: p.name.lower())
    subfolders = sorted(
        [d for d in folder.iterdir() if d.is_dir()],
        key=lambda d: d.name.lower(),
    )

    lines: list[str] = []
    lines.append(AUTOGEN_NOTICE)
    lines.append("# ContentCenter\n")
    lines.append(
        f"> Auto-generated index — {today}. "
        "Shared library of reusable Inventor components.\n"
    )

    lines.append("## Library Categories\n")
    if subfolders:
        for d in subfolders:
            lines.append(f"- `{d.name}/`")
        lines.append("")

    lines.append("## Summary\n")
    lines.append(f"- **Assemblies (`.iam`):** {len(iams)}")
    lines.append(f"- **Parts (`.ipt`):** {len(ipts)}\n")

    lines.append("## Notes\n")
    lines.append(
        "This folder is the shared ContentCenter library for the PIHTI project.\n"
        "Components here are referenced by assemblies throughout the workspace.\n"
    )

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# .gitignore
# ---------------------------------------------------------------------------

def write_gitignore(root: Path, dry_run: bool) -> None:
    target = root / ".gitignore"
    if target.exists():
        existing = target.read_text(encoding="utf-8")
        # Check if our marker is already present
        if "Autodesk Inventor cache" in existing:
            print("  [skip]  .gitignore already contains Inventor rules")
            return
        new_content = existing.rstrip("\n") + "\n\n" + GITIGNORE_RULES
        action = "update"
    else:
        new_content = GITIGNORE_RULES
        action = "create"

    print(f"  [{action}] .gitignore")
    if not dry_run:
        target.write_text(new_content, encoding="utf-8")


# ---------------------------------------------------------------------------
# INDEX.md
# ---------------------------------------------------------------------------

def render_index(root: Path, index_entries: list[tuple[Path, Path | None]]) -> str:
    today = datetime.date.today().isoformat()
    lines: list[str] = []
    lines.append(AUTOGEN_NOTICE)
    lines.append("# PIHTI — Project Index\n")
    lines.append(
        f"> Auto-generated on {today}. "
        "Lists all folders containing Inventor assemblies.\n"
    )
    lines.append("| Folder | Main Assembly |")
    lines.append("|--------|---------------|")
    for folder, main in sorted(index_entries, key=lambda e: str(e[0]).lower()):
        rel_folder = os.path.relpath(folder, root).replace("\\", "/")
        readme_link = f"[{rel_folder}]({rel_folder}/README.md)"
        main_cell = f"`{main.name}`" if main else "_—_"
        lines.append(f"| {readme_link} | {main_cell} |")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main scan + generate
# ---------------------------------------------------------------------------

def run(
    root: Path,
    dry_run: bool,
    generate_index: bool,
    *,
    existing_only: bool = False,
) -> None:
    root = root.resolve()
    print(f"Root: {root}")
    if dry_run:
        print("  ** DRY RUN — no files will be written **\n")

    content_center = root / "ContentCenter"
    index_entries: list[tuple[Path, Path | None]] = []
    refreshed_folders: set[Path] = set()

    # A refresh-only migration touches marker-owned Markdown and nothing else.
    if not existing_only:
        write_gitignore(root, dry_run)

    # Refresh every surviving marker-owned README first, even if the folder no
    # longer meets today's creation heuristic. This is the migration path for
    # older generator templates; authored files have no marker and are never
    # admitted here.
    for readme in sorted(root.rglob("README.md"), key=lambda path: str(path).casefold()):
        folder = readme.parent
        if folder == root or is_vendor_path(folder, root) or is_manually_edited(readme):
            continue
        if folder == content_center:
            render = partial(render_content_center_readme, folder)
        else:
            iams, ipts = collect_iams_ipts(folder)
            render = partial(render_readme, folder, iams, ipts)
        write_generated(readme, render, root, dry_run, create=False)
        refreshed_folders.add(folder)

    # --- Walk all directories ----------------------------------------------
    all_dirs = sorted(root.rglob("*"), key=lambda p: str(p).lower())
    visited_dirs: set[Path] = set()

    for path in all_dirs:
        if not path.is_dir():
            continue
        # Skip OldVersions everywhere
        if "OldVersions" in path.parts:
            continue
        folder = path

        # --- ContentCenter special handling --------------------------------
        if folder == content_center:
            if folder not in refreshed_folders:
                write_generated(
                    folder / "README.md",
                    lambda folder=folder: render_content_center_readme(folder),
                    root,
                    dry_run,
                    create=not existing_only,
                )
            visited_dirs.add(folder)
            continue

        if is_content_center(folder, root):
            # skip all ContentCenter subfolders
            continue

        # Skip vendor / imported-component subtrees (STEP, STEPs, stp, …)
        if is_vendor_path(folder, root):
            continue

        # --- Regular folders -----------------------------------------------
        iams, ipts = collect_iams_ipts(folder)

        if not iams:
            continue

        # Noise suppression: skip single-component / helper folders
        if not is_meaningful_folder(folder, root, iams, ipts):
            print(f"  [noise]  {folder.relative_to(root)}")
            continue

        if folder not in refreshed_folders:
            write_generated(
                folder / "README.md",
                lambda folder=folder, iams=iams, ipts=ipts: render_readme(
                    folder, iams, ipts
                ),
                root,
                dry_run,
                create=not existing_only,
            )

        main = find_main_iam(iams)
        index_entries.append((folder, main))

    # --- INDEX.md ----------------------------------------------------------
    if generate_index:
        write_generated(
            root / "INDEX.md",
            lambda: render_index(root, index_entries),
            root,
            dry_run,
            create=not existing_only,
        )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate README.md files for an Autodesk Inventor workspace."
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="Path to the repository root (default: parent of this script's folder)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned actions without writing any files",
    )
    parser.add_argument(
        "--no-index",
        dest="index",
        action="store_false",
        help="Skip generating INDEX.md at the repository root",
    )
    parser.add_argument(
        "--refresh-only",
        action="store_true",
        help="Refresh marker-owned files but do not create new README.md or INDEX.md files",
    )
    parser.set_defaults(index=True)
    args = parser.parse_args()
    run(args.root, args.dry_run, args.index, existing_only=args.refresh_only)


if __name__ == "__main__":
    main()
